version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_SUREDBITS_WALLET_IP
      APP_PORT: 3002

  web:
    image: bitcoinscala/wallet-server-ui:1.9.3@sha256:dfbded611403fb03dac45fe915320079933e8f864e0942b7fb3ddea017e2b8dd
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/wallet:/bitcoin-s
      - ${APP_DATA_DIR}/data/log:/log
    environment:
      LOG_PATH: "/log/"
      BITCOIN_S_HOME: "/bitcoin-s/"
     #MEMPOOL_API_URL: "http://umbrel.local:${APP_MEMPOOL_PORT}/api"
      WALLET_SERVER_API_URL: "http://${APP_SUREDBITS_WALLET_SERVER_IP}:9999/"
      WALLET_SERVER_WS: "ws://${APP_SUREDBITS_WALLET_SERVER_IP}:19999/events"
      TOR_PROXY: socks5://${TOR_PROXY_IP}:${TOR_PROXY_PORT}
      DEFAULT_UI_PASSWORD: "none" 
      BITCOIN_S_SERVER_RPC_PASSWORD: $APP_PASSWORD
    networks:
      default:
        ipv4_address: $APP_SUREDBITS_WALLET_IP
    depends_on: 
      - walletserver
  
  walletserver:
    image: bitcoinscala/bitcoin-s-server:1.9.3@sha256:db995d23ed6cd5a31de5fffe06c6edff5c420c77b63440169c41c2016c89993c
    entrypoint: ["/opt/docker/bin/bitcoin-s-server", "--datadir", "/bitcoin-s", "--conf", "/opt/docker/docker-application.conf"]
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/wallet:/bitcoin-s
    environment:
      BITCOIN_S_NODE_MODE: "bitcoind"
      BITCOIN_S_NETWORK: $APP_BITCOIN_NETWORK
      BITCOIN_S_KEYMANAGER_ENTROPY: $APP_SEED  
      BITCOIN_S_PROXY_ENABLED: "false"
      BITCOIN_S_TOR_ENABLED: "false"
      BITCOIN_S_TOR_PROVIDED: "true"
      BITCOIN_S_DLCNODE_PROXY_ENABLED: "true"
      BITCOIN_S_DLCNODE_PROXY_SOCKS5: "${TOR_PROXY_IP}:${TOR_PROXY_PORT}"
      BITCOIN_S_DLCNODE_EXTERNAL_IP: $APP_SUREDBITS_WALLET_P2P_HIDDEN_SERVICE
      BITCOIN_S_BITCOIND_HOST: $APP_BITCOIN_NODE_IP
      BITCOIN_S_BITCOIND_PORT: $APP_BITCOIN_RPC_PORT
      BITCOIN_S_BITCOIND_USER: $APP_BITCOIN_RPC_USER
      BITCOIN_S_BITCOIND_PASSWORD: $APP_BITCOIN_RPC_PASS
      BITCOIN_S_SERVER_RPC_PASSWORD: $APP_PASSWORD
      JAVA_OPTS: "-Xmx756m"
      DISABLE_JLINK: "1"
    ports:
      - "$APP_SUREDBITS_WALLET_P2P_PORT:$APP_SUREDBITS_WALLET_P2P_PORT"
    networks:
      default:
        ipv4_address: $APP_SUREDBITS_WALLET_SERVER_IP
